/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaEstoque.views;

import SistemaEstoque.database.Database;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author Rafael
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();

        System.out.println("Width: " + getWidth());
        System.out.println("Height: " + getHeight());
        
        Database db = new Database();
        db.exibir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fCaixa = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuConsultaProduto = new javax.swing.JMenuItem();
        menuCadastrarNovoProduto = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema");
        setPreferredSize(new java.awt.Dimension(1366, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(820, 529));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        fCaixa.setText("Financeiro");

        jMenuItem1.setText("Caixa");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        fCaixa.add(jMenuItem1);

        jMenuBar1.add(fCaixa);

        jMenu3.setText("Estoque");

        menuConsultaProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        menuConsultaProduto.setText("Consulta de Produto");
        menuConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaProdutoActionPerformed(evt);
            }
        });
        jMenu3.add(menuConsultaProduto);

        menuCadastrarNovoProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        menuCadastrarNovoProduto.setText("Cadastrar Novo Produto");
        menuCadastrarNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarNovoProdutoActionPerformed(evt);
            }
        });
        jMenu3.add(menuCadastrarNovoProduto);

        jMenuItem11.setText("Remover Produto do Estoque");
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        jMenuItem6.setText("Fluxo de Caixa");
        jMenu4.add(jMenuItem6);

        jMenuItem7.setText("Vendas do Dia");
        jMenu4.add(jMenuItem7);

        jMenuItem8.setText("Movimentação de Estoque");
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Pedidos");

        jMenuItem3.setText("Nova Venda");
        jMenu5.add(jMenuItem3);

        jMenuItem4.setText("Reservas");
        jMenu5.add(jMenuItem4);

        jMenuItem5.setText("Cancelamento de Pedido");
        jMenu5.add(jMenuItem5);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Sistema");

        jMenuItem14.setText("Manutenção");
        jMenu2.add(jMenuItem14);

        jMenuItem13.setText("Usuarios");
        jMenu2.add(jMenuItem13);

        jMenuItem12.setText("Ajuda");
        jMenu2.add(jMenuItem12);

        jMenuItem2.setText("Sair");
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Caixa c = new Caixa();
        c.setVisible(true);


    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaProdutoActionPerformed
        ConsultaDeProduto consulta = new ConsultaDeProduto();
//        consulta.setSize(new Dimension(800, 600));
//        
//         // Get the size of the screen
//        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
//        
//        int w = this.getSize().width;
//        int h = this.getSize().height;
//        int x = (dim.width-w)/2;
//        int y = (dim.height-h)/2;
//
//        // Move the window
//        consulta.setLocation(x, y);
        consulta.setVisible(true);
    }//GEN-LAST:event_menuConsultaProdutoActionPerformed

    private void menuCadastrarNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarNovoProdutoActionPerformed

        CadastrarNovoProduto cadastrar = new CadastrarNovoProduto();
        cadastrar.setVisible(true);

    }//GEN-LAST:event_menuCadastrarNovoProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);

            }
        });
    }

    public void imagensBtn() {
        //        Icon pesquisar = new ImageIcon(getClass().getResource("../img/pesquisar.png"));
//        Icon icon = new ImageIcon(getClass().getResource("../img/add.png"));
//        icon.getIconHeight();
//        icon.getIconWidth();
//        
//        System.out.println(icon.getIconHeight() +"   "+ icon.getIconWidth() );

//        JButton buttonImage = new JButton(pesquisar);
//
//        buttonImage.setBounds(20, 20, 64, 62);
//        
//        jPanel2.add(buttonImage);
//        botao1.setIcon(pesquisar);
//        botao2.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu fCaixa;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem menuCadastrarNovoProduto;
    private javax.swing.JMenuItem menuConsultaProduto;
    // End of variables declaration//GEN-END:variables
}
